var express = require('express');
var router = express.Router();
var fs = require('fs');
var wkhtmltopdf = require('wkhtmltopdf');

var sampleData = {
      "spatialFilter": {
        "src": "http://maps-t.monsanto.com/arcgis/rest/directories/arcgisoutput/Utilities/PrintingTools_GPServer/_ags_815ba20d2e9b46b0b1a7a0ef647192a3.png"
      },
      "criteria": [{
        "title": "Check Products",
        "value": "DKC60-67RIB, DKC61-16RIB, DKC61-54RIB, DKC62-98RIB, DKC62-78RIB, DKC63-87RIB"
      }, {
        "title": "Other Products",
        "value": "P0993AM1, P1151XR, P1690AM, P1365, P1271AM, P1324HR, P1151AM1, P0636AM1, P0407AMXT, P1197AM, P1197CHR, P1142AMX, P1257AM, P1768AMX, P0636HR, P0969AM, P0801AM, P0987AM1, P1625CHR, P0876CHR, P1555CHR, P0993XR, P1690CHR, 33D53 AM1, P1690HR, P1151AMX, P1498AM, P0636AM, P2088AM, P1498AM1, P1151AM, P0832AM1, P1365AMX, P1360HR, 33D42-INTRASECT, P1023AM-R, P1266AM, P1151HR, P1105AM, P0805AM"
      }, {
        "title": "Years Examined",
        "value": "2014"
      }, {
        "title": "Test Types",
        "value": "FTN"
      }],
      "legal": "/images/legal-Dekalb-Corn.jpg",
      "logo": "/images/dekalb-logo.jpg",
      "tableData": {
        "rows": [{
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0636AM1",
          "compTraits": "AM1",
          "compRM": 106,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "203.8",
          "Other_YIELD": 195.3,
          "Advantage_YIELD": "8.5",
          "Check_HARVEST MOISTURE": "16.1",
          "Other_HARVEST MOISTURE": 15.3,
          "Advantage_HARVEST MOISTURE": "-0.9",
          "Check_GROSS INCOME": "754.93",
          "Other_GROSS INCOME": 730.16,
          "Advantage_GROSS INCOME": "24.77",
          "$$hashKey": "object:8787"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AMX",
          "compTraits": "AMX",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "44.0",
          "comps": 19,
          "checkWins": 11,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "229.1",
          "Other_YIELD": 226.8,
          "Advantage_YIELD": "2.2",
          "Check_HARVEST MOISTURE": "17.2",
          "Other_HARVEST MOISTURE": 17.4,
          "Advantage_HARVEST MOISTURE": "0.2",
          "Check_GROSS INCOME": "838.74",
          "Other_GROSS INCOME": 828.84,
          "Advantage_GROSS INCOME": "9.90",
          "$$hashKey": "object:8788"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0407AMXT",
          "compTraits": "AMXT",
          "compRM": 104,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "214.6",
          "Other_YIELD": 182.6,
          "Advantage_YIELD": "32.0",
          "Check_HARVEST MOISTURE": "18.2",
          "Other_HARVEST MOISTURE": 16.5,
          "Advantage_HARVEST MOISTURE": "-1.7",
          "Check_GROSS INCOME": "777.48",
          "Other_GROSS INCOME": 673.72,
          "Advantage_GROSS INCOME": "103.76",
          "$$hashKey": "object:8789"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "33D53 AM1",
          "compTraits": "AM1",
          "compRM": 115,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "233.4",
          "Other_YIELD": 221.7,
          "Advantage_YIELD": "11.8",
          "Check_HARVEST MOISTURE": "14.9",
          "Other_HARVEST MOISTURE": 15.2,
          "Advantage_HARVEST MOISTURE": "0.3",
          "Check_GROSS INCOME": "875.30",
          "Other_GROSS INCOME": 829.34,
          "Advantage_GROSS INCOME": "45.96",
          "$$hashKey": "object:8790"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690AM",
          "compTraits": "AM",
          "compRM": 116,
          "compPT": null,
          "winPercentage": "26.3",
          "comps": 13,
          "checkWins": 5,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "214.0",
          "Other_YIELD": 219.1,
          "Advantage_YIELD": "-5.2",
          "Check_HARVEST MOISTURE": "16.8",
          "Other_HARVEST MOISTURE": 18.1,
          "Advantage_HARVEST MOISTURE": "1.3",
          "Check_GROSS INCOME": "787.09",
          "Other_GROSS INCOME": 794.69,
          "Advantage_GROSS INCOME": "-7.60",
          "$$hashKey": "object:8791"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1498AM",
          "compTraits": "AM",
          "compRM": 114,
          "compPT": null,
          "winPercentage": "63.2",
          "comps": 14,
          "checkWins": 12,
          "years": "14, 15",
          "isSummary": false,
          "Check_YIELD": "217.7",
          "Other_YIELD": 204.5,
          "Advantage_YIELD": "13.2",
          "Check_HARVEST MOISTURE": "18.4",
          "Other_HARVEST MOISTURE": 19.6,
          "Advantage_HARVEST MOISTURE": "1.2",
          "Check_GROSS INCOME": "786.71",
          "Other_GROSS INCOME": 729.17,
          "Advantage_GROSS INCOME": "57.54",
          "$$hashKey": "object:8792"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "33D42-INTRASECT",
          "compTraits": "INTRASECT",
          "compRM": 115,
          "compPT": null,
          "winPercentage": "57.1",
          "comps": 6,
          "checkWins": 4,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "208.5",
          "Other_YIELD": 207.3,
          "Advantage_YIELD": "1.3",
          "Check_HARVEST MOISTURE": "16.8",
          "Other_HARVEST MOISTURE": 17.8,
          "Advantage_HARVEST MOISTURE": "1.0",
          "Check_GROSS INCOME": "767.01",
          "Other_GROSS INCOME": 754.21,
          "Advantage_GROSS INCOME": "12.81"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 116,
          "compPT": null,
          "winPercentage": 0,
          "comps": 3,
          "checkWins": 0,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "233.4",
          "Other_YIELD": 248.6,
          "Advantage_YIELD": "-15.2",
          "Check_HARVEST MOISTURE": "14.9",
          "Other_HARVEST MOISTURE": 16,
          "Advantage_HARVEST MOISTURE": "1.2",
          "Check_GROSS INCOME": "875.30",
          "Other_GROSS INCOME": 921.96,
          "Advantage_GROSS INCOME": "-46.65"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1257AM",
          "compTraits": "AM",
          "compRM": 112,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "201.7",
          "Other_YIELD": 222.7,
          "Advantage_YIELD": "-21.0",
          "Check_HARVEST MOISTURE": "18.3",
          "Other_HARVEST MOISTURE": 17.6,
          "Advantage_HARVEST MOISTURE": "-0.7",
          "Check_GROSS INCOME": "729.80",
          "Other_GROSS INCOME": 812.27,
          "Advantage_GROSS INCOME": "-82.47"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AM1",
          "compTraits": "AM1",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "41.7",
          "comps": 43,
          "checkWins": 25,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "292.8",
          "Other_YIELD": 286.9,
          "Advantage_YIELD": "6.0",
          "Check_HARVEST MOISTURE": "24.0",
          "Other_HARVEST MOISTURE": 23.9,
          "Advantage_HARVEST MOISTURE": "-0.1",
          "Check_GROSS INCOME": "992.76",
          "Other_GROSS INCOME": 974.05,
          "Advantage_GROSS INCOME": "18.71"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AM",
          "compTraits": "AM",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "31.7",
          "comps": 30,
          "checkWins": 13,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "221.8",
          "Other_YIELD": 225.3,
          "Advantage_YIELD": "-3.4",
          "Check_HARVEST MOISTURE": "17.7",
          "Other_HARVEST MOISTURE": 17.6,
          "Advantage_HARVEST MOISTURE": "-0.2",
          "Check_GROSS INCOME": "807.40",
          "Other_GROSS INCOME": 821.61,
          "Advantage_GROSS INCOME": "-14.20"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1498AM1",
          "compTraits": "AM1",
          "compRM": 114,
          "compPT": null,
          "winPercentage": "50.0",
          "comps": 45,
          "checkWins": 31,
          "years": "14, 15",
          "isSummary": false,
          "Check_YIELD": "274.2",
          "Other_YIELD": 265.4,
          "Advantage_YIELD": "8.8",
          "Check_HARVEST MOISTURE": "22.9",
          "Other_HARVEST MOISTURE": 24.1,
          "Advantage_HARVEST MOISTURE": "1.2",
          "Check_GROSS INCOME": "941.80",
          "Other_GROSS INCOME": 898.69,
          "Advantage_GROSS INCOME": "43.11"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "205.6",
          "Other_YIELD": 204.5,
          "Advantage_YIELD": "1.1",
          "Check_HARVEST MOISTURE": "18.4",
          "Other_HARVEST MOISTURE": 17.7,
          "Advantage_HARVEST MOISTURE": "-0.7",
          "Check_GROSS INCOME": "743.10",
          "Other_GROSS INCOME": 744.81,
          "Advantage_GROSS INCOME": "-1.71"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1365AMX",
          "compTraits": "AMXR",
          "compRM": 113,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "242.5",
          "Other_YIELD": 243.9,
          "Advantage_YIELD": "-1.4",
          "Check_HARVEST MOISTURE": "16.2",
          "Other_HARVEST MOISTURE": 17.6,
          "Advantage_HARVEST MOISTURE": "1.4",
          "Check_GROSS INCOME": "897.52",
          "Other_GROSS INCOME": 889.17,
          "Advantage_GROSS INCOME": "8.35"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1197CHR",
          "compTraits": "CHR",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "16.7",
          "comps": 5,
          "checkWins": 1,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "237.7",
          "Other_YIELD": 252.8,
          "Advantage_YIELD": "-15.1",
          "Check_HARVEST MOISTURE": "19.6",
          "Other_HARVEST MOISTURE": 19.7,
          "Advantage_HARVEST MOISTURE": "0.1",
          "Check_GROSS INCOME": "848.04",
          "Other_GROSS INCOME": 900.91,
          "Advantage_GROSS INCOME": "-52.87"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1324HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 113,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "203.8",
          "Other_YIELD": 187.1,
          "Advantage_YIELD": "16.7",
          "Check_HARVEST MOISTURE": "16.1",
          "Other_HARVEST MOISTURE": 16,
          "Advantage_HARVEST MOISTURE": "-0.1",
          "Check_GROSS INCOME": "754.93",
          "Other_GROSS INCOME": 693.92,
          "Advantage_GROSS INCOME": "61.01"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0805AM",
          "compTraits": "AM",
          "compRM": 108,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "201.7",
          "Other_YIELD": 211.7,
          "Advantage_YIELD": "-10.0",
          "Check_HARVEST MOISTURE": "18.3",
          "Other_HARVEST MOISTURE": 17.5,
          "Advantage_HARVEST MOISTURE": "-0.7",
          "Check_GROSS INCOME": "729.80",
          "Other_GROSS INCOME": 772.2,
          "Advantage_GROSS INCOME": "-42.40"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0636AM",
          "compTraits": "AM",
          "compRM": 106,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "195.5",
          "Other_YIELD": 163.7,
          "Advantage_YIELD": "31.8",
          "Check_HARVEST MOISTURE": "16.5",
          "Other_HARVEST MOISTURE": 14.1,
          "Advantage_HARVEST MOISTURE": "-2.4",
          "Check_GROSS INCOME": "721.53",
          "Other_GROSS INCOME": 613.86,
          "Advantage_GROSS INCOME": "107.67"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0993AM1",
          "compTraits": "AM1",
          "compRM": 109,
          "compPT": null,
          "winPercentage": "64.0",
          "comps": 19,
          "checkWins": 16,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "213.0",
          "Other_YIELD": 203.2,
          "Advantage_YIELD": "9.8",
          "Check_HARVEST MOISTURE": "17.8",
          "Other_HARVEST MOISTURE": 15.7,
          "Advantage_HARVEST MOISTURE": "-2.1",
          "Check_GROSS INCOME": "774.67",
          "Other_GROSS INCOME": 756.26,
          "Advantage_GROSS INCOME": "18.41"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1365",
          "compTraits": "AMX",
          "compRM": 113,
          "compPT": null,
          "winPercentage": "50.0",
          "comps": 1,
          "checkWins": 1,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "230.1",
          "Other_YIELD": 220.3,
          "Advantage_YIELD": "9.7",
          "Check_HARVEST MOISTURE": "15.2",
          "Other_HARVEST MOISTURE": 16.1,
          "Advantage_HARVEST MOISTURE": "0.9",
          "Check_GROSS INCOME": "861.00",
          "Other_GROSS INCOME": 816.48,
          "Advantage_GROSS INCOME": "44.53"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1266AM",
          "compTraits": "AM",
          "compRM": 112,
          "compPT": null,
          "winPercentage": "38.1",
          "comps": 69,
          "checkWins": 37,
          "years": "14, 15",
          "isSummary": false,
          "Check_YIELD": "297.4",
          "Other_YIELD": 297.3,
          "Advantage_YIELD": "0.2",
          "Check_HARVEST MOISTURE": "24.5",
          "Other_HARVEST MOISTURE": 24,
          "Advantage_HARVEST MOISTURE": "-0.6",
          "Check_GROSS INCOME": "1001.92",
          "Other_GROSS INCOME": 1008.08,
          "Advantage_GROSS INCOME": "-6.16"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690CHR",
          "compTraits": "CHR",
          "compRM": 116,
          "compPT": null,
          "winPercentage": "29.6",
          "comps": 59,
          "checkWins": 24,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "346.9",
          "Other_YIELD": 358.9,
          "Advantage_YIELD": "-12.0",
          "Check_HARVEST MOISTURE": "25.9",
          "Other_HARVEST MOISTURE": 28.9,
          "Advantage_HARVEST MOISTURE": "3.0",
          "Check_GROSS INCOME": "1149.93",
          "Other_GROSS INCOME": 1146.25,
          "Advantage_GROSS INCOME": "3.68"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1197AM",
          "compTraits": "AM",
          "compRM": 111,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "201.7",
          "Other_YIELD": 229.6,
          "Advantage_YIELD": "-27.9",
          "Check_HARVEST MOISTURE": "18.3",
          "Other_HARVEST MOISTURE": 18.2,
          "Advantage_HARVEST MOISTURE": "-0.1",
          "Check_GROSS INCOME": "729.80",
          "Other_GROSS INCOME": 831.54,
          "Advantage_GROSS INCOME": "-101.73"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1271AM",
          "compTraits": "AM",
          "compRM": 112,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "201.7",
          "Other_YIELD": 218.4,
          "Advantage_YIELD": "-16.7",
          "Check_HARVEST MOISTURE": "18.3",
          "Other_HARVEST MOISTURE": 19.1,
          "Advantage_HARVEST MOISTURE": "0.8",
          "Check_GROSS INCOME": "729.80",
          "Other_GROSS INCOME": 783.57,
          "Advantage_GROSS INCOME": "-53.77"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1105AM",
          "compTraits": "AM",
          "compRM": 110,
          "compPT": null,
          "winPercentage": "7.4",
          "comps": 19,
          "checkWins": 2,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "336.0",
          "Other_YIELD": 353.6,
          "Advantage_YIELD": "-17.6",
          "Check_HARVEST MOISTURE": "23.6",
          "Other_HARVEST MOISTURE": 25.2,
          "Advantage_HARVEST MOISTURE": "1.6",
          "Check_GROSS INCOME": "1144.89",
          "Other_GROSS INCOME": 1182.27,
          "Advantage_GROSS INCOME": "-37.37"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0801AM",
          "compTraits": "AM",
          "compRM": 108,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "201.7",
          "Other_YIELD": 228,
          "Advantage_YIELD": "-26.3",
          "Check_HARVEST MOISTURE": "18.3",
          "Other_HARVEST MOISTURE": 17.4,
          "Advantage_HARVEST MOISTURE": "-0.9",
          "Check_GROSS INCOME": "729.80",
          "Other_GROSS INCOME": 833.1,
          "Advantage_GROSS INCOME": "-103.30"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-54RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1360HR",
          "compTraits": "RR/HX1/LL",
          "compRM": 113,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "200.6",
          "Other_YIELD": 203.7,
          "Advantage_YIELD": "-3.1",
          "Check_HARVEST MOISTURE": "19.7",
          "Other_HARVEST MOISTURE": 20,
          "Advantage_HARVEST MOISTURE": "0.3",
          "Check_GROSS INCOME": "714.32",
          "Other_GROSS INCOME": 722.89,
          "Advantage_GROSS INCOME": "-8.56"
        }, {
          "Check_YIELD": "273.8",
          "Check_HARVEST MOISTURE": "21.8",
          "Check_GROSS INCOME": "946.04",
          "Other_YIELD": 274.22228116710875,
          "Other_HARVEST MOISTURE": 22.353580901856763,
          "Other_GROSS INCOME": 939.0934482758623,
          "Advantage_YIELD": "-0.4",
          "Advantage_HARVEST MOISTURE": "0.5",
          "Advantage_GROSS INCOME": "6.95",
          "comps": 377,
          "winPercentage": "38.8",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "",
          "compBrand": "",
          "compProdBrand": "",
          "compTraits": "",
          "compRM": "",
          "compPT": "",
          "years": "",
          "isSummary": true
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0801AM",
          "compTraits": "AM",
          "compRM": 108,
          "compPT": null,
          "winPercentage": 0,
          "comps": 3,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "218.4",
          "Other_YIELD": 232.9,
          "Advantage_YIELD": "-14.5",
          "Check_HARVEST MOISTURE": "15.9",
          "Other_HARVEST MOISTURE": 17.4,
          "Advantage_HARVEST MOISTURE": "1.5",
          "Check_GROSS INCOME": "810.96",
          "Other_GROSS INCOME": 850.75,
          "Advantage_GROSS INCOME": "-39.79"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0636HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 106,
          "compPT": null,
          "winPercentage": "66.7",
          "comps": 2,
          "checkWins": 2,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "177.7",
          "Other_YIELD": 163.4,
          "Advantage_YIELD": "14.3",
          "Check_HARVEST MOISTURE": "22.2",
          "Other_HARVEST MOISTURE": 21.9,
          "Advantage_HARVEST MOISTURE": "-0.3",
          "Check_GROSS INCOME": "615.08",
          "Other_GROSS INCOME": 567.4,
          "Advantage_GROSS INCOME": "47.68"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1023AM-R",
          "compTraits": "AMR",
          "compRM": 110,
          "compPT": null,
          "winPercentage": "60.0",
          "comps": 4,
          "checkWins": 3,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "242.6",
          "Other_YIELD": 238.3,
          "Advantage_YIELD": "4.3",
          "Check_HARVEST MOISTURE": "16.4",
          "Other_HARVEST MOISTURE": 16.7,
          "Advantage_HARVEST MOISTURE": "0.3",
          "Check_GROSS INCOME": "896.06",
          "Other_GROSS INCOME": 877.21,
          "Advantage_GROSS INCOME": "18.85"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0876CHR",
          "compTraits": "CHR",
          "compRM": 108,
          "compPT": null,
          "winPercentage": "72.2",
          "comps": 13,
          "checkWins": 13,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "254.4",
          "Other_YIELD": 234.6,
          "Advantage_YIELD": "19.9",
          "Check_HARVEST MOISTURE": "17.2",
          "Other_HARVEST MOISTURE": 18,
          "Advantage_HARVEST MOISTURE": "0.8",
          "Check_GROSS INCOME": "931.91",
          "Other_GROSS INCOME": 851.7,
          "Advantage_GROSS INCOME": "80.21"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0993XR",
          "compTraits": "RR2/HXX/LL",
          "compRM": 109,
          "compPT": null,
          "winPercentage": 0,
          "comps": 1,
          "checkWins": 0,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "199.2",
          "Other_YIELD": 206.8,
          "Advantage_YIELD": "-7.7",
          "Check_HARVEST MOISTURE": "19.5",
          "Other_HARVEST MOISTURE": 19,
          "Advantage_HARVEST MOISTURE": "-0.6",
          "Check_GROSS INCOME": "710.64",
          "Other_GROSS INCOME": 742.96,
          "Advantage_GROSS INCOME": "-32.32"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 116,
          "compPT": null,
          "winPercentage": 0,
          "comps": 7,
          "checkWins": 0,
          "years": "13, 14",
          "isSummary": false,
          "Check_YIELD": "241.3",
          "Other_YIELD": 253.8,
          "Advantage_YIELD": "-12.5",
          "Check_HARVEST MOISTURE": "15.9",
          "Other_HARVEST MOISTURE": 17.6,
          "Advantage_HARVEST MOISTURE": "1.6",
          "Check_GROSS INCOME": "895.89",
          "Other_GROSS INCOME": 925.63,
          "Advantage_GROSS INCOME": "-29.74"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AM",
          "compTraits": "AM",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "51.6",
          "comps": 69,
          "checkWins": 49,
          "years": "13, 14, 15",
          "isSummary": false,
          "Check_YIELD": "279.1",
          "Other_YIELD": 258.5,
          "Advantage_YIELD": "20.5",
          "Check_HARVEST MOISTURE": "24.1",
          "Other_HARVEST MOISTURE": 24.3,
          "Advantage_HARVEST MOISTURE": "0.1",
          "Check_GROSS INCOME": "944.31",
          "Other_GROSS INCOME": 873.83,
          "Advantage_GROSS INCOME": "70.49"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1498AM1",
          "compTraits": "AM1",
          "compRM": 114,
          "compPT": null,
          "winPercentage": "58.3",
          "comps": 78,
          "checkWins": 64,
          "years": "13, 14, 15",
          "isSummary": false,
          "Check_YIELD": "316.8",
          "Other_YIELD": 289.3,
          "Advantage_YIELD": "27.5",
          "Check_HARVEST MOISTURE": "23.8",
          "Other_HARVEST MOISTURE": 25.9,
          "Advantage_HARVEST MOISTURE": "2.2",
          "Check_GROSS INCOME": "1076.85",
          "Other_GROSS INCOME": 958.36,
          "Advantage_GROSS INCOME": "118.48"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0987AM1",
          "compTraits": "AM1",
          "compRM": 109,
          "compPT": null,
          "winPercentage": "42.9",
          "comps": 10,
          "checkWins": 6,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "268.4",
          "Other_YIELD": 259.7,
          "Advantage_YIELD": "8.7",
          "Check_HARVEST MOISTURE": "20.5",
          "Other_HARVEST MOISTURE": 21.6,
          "Advantage_HARVEST MOISTURE": "1.1",
          "Check_GROSS INCOME": "947.63",
          "Other_GROSS INCOME": 905.47,
          "Advantage_GROSS INCOME": "42.16"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0636AM1",
          "compTraits": "AM1",
          "compRM": 106,
          "compPT": null,
          "winPercentage": "66.7",
          "comps": 9,
          "checkWins": 8,
          "years": "13, 14",
          "isSummary": false,
          "Check_YIELD": "188.9",
          "Other_YIELD": 181.1,
          "Advantage_YIELD": "7.8",
          "Check_HARVEST MOISTURE": "18.1",
          "Other_HARVEST MOISTURE": 17.9,
          "Advantage_HARVEST MOISTURE": "-0.2",
          "Check_GROSS INCOME": "685.31",
          "Other_GROSS INCOME": 658.17,
          "Advantage_GROSS INCOME": "27.14"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0636AM",
          "compTraits": "AM",
          "compRM": 106,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "204.8",
          "Other_YIELD": 163.7,
          "Advantage_YIELD": "41.2",
          "Check_HARVEST MOISTURE": "16.7",
          "Other_HARVEST MOISTURE": 14.1,
          "Advantage_HARVEST MOISTURE": "-2.6",
          "Check_GROSS INCOME": "754.47",
          "Other_GROSS INCOME": 613.86,
          "Advantage_GROSS INCOME": "140.61"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1555CHR",
          "compTraits": "CHR",
          "compRM": 115,
          "compPT": null,
          "winPercentage": "25.0",
          "comps": 3,
          "checkWins": 1,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "235.9",
          "Other_YIELD": 244.9,
          "Advantage_YIELD": "-9.0",
          "Check_HARVEST MOISTURE": "18.9",
          "Other_HARVEST MOISTURE": 21,
          "Advantage_HARVEST MOISTURE": "2.0",
          "Check_GROSS INCOME": "847.82",
          "Other_GROSS INCOME": 860.18,
          "Advantage_GROSS INCOME": "-12.36"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0407AMXT",
          "compTraits": "AMXT",
          "compRM": 104,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "214.4",
          "Other_YIELD": 182.6,
          "Advantage_YIELD": "31.8",
          "Check_HARVEST MOISTURE": "17.4",
          "Other_HARVEST MOISTURE": 16.5,
          "Advantage_HARVEST MOISTURE": "-0.9",
          "Check_GROSS INCOME": "783.39",
          "Other_GROSS INCOME": 673.72,
          "Advantage_GROSS INCOME": "109.67"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "33D42-INTRASECT",
          "compTraits": "INTRASECT",
          "compRM": 115,
          "compPT": null,
          "winPercentage": "50.0",
          "comps": 8,
          "checkWins": 5,
          "years": "13, 14",
          "isSummary": false,
          "Check_YIELD": "304.2",
          "Other_YIELD": 296.3,
          "Advantage_YIELD": "7.9",
          "Check_HARVEST MOISTURE": "22.5",
          "Other_HARVEST MOISTURE": 24.2,
          "Advantage_HARVEST MOISTURE": "1.8",
          "Check_GROSS INCOME": "1050.04",
          "Other_GROSS INCOME": 1001.74,
          "Advantage_GROSS INCOME": "48.30"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1257AM",
          "compTraits": "AM",
          "compRM": 112,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "217.7",
          "Other_YIELD": 222.7,
          "Advantage_YIELD": "-5.0",
          "Check_HARVEST MOISTURE": "16.0",
          "Other_HARVEST MOISTURE": 17.6,
          "Advantage_HARVEST MOISTURE": "1.6",
          "Check_GROSS INCOME": "807.95",
          "Other_GROSS INCOME": 812.27,
          "Advantage_GROSS INCOME": "-4.33"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1768AMX",
          "compTraits": "AMX",
          "compRM": 117,
          "compPT": null,
          "winPercentage": "50.0",
          "comps": 1,
          "checkWins": 1,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "169.8",
          "Other_YIELD": 167.1,
          "Advantage_YIELD": "2.7",
          "Check_HARVEST MOISTURE": "17.6",
          "Other_HARVEST MOISTURE": 19,
          "Advantage_HARVEST MOISTURE": "1.4",
          "Check_GROSS INCOME": "619.48",
          "Other_GROSS INCOME": 600.29,
          "Advantage_GROSS INCOME": "19.19"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0832AM1",
          "compTraits": "AM1",
          "compRM": 108,
          "compPT": null,
          "winPercentage": "60.0",
          "comps": 3,
          "checkWins": 3,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "250.6",
          "Other_YIELD": 236.2,
          "Advantage_YIELD": "14.4",
          "Check_HARVEST MOISTURE": "16.6",
          "Other_HARVEST MOISTURE": 16.5,
          "Advantage_HARVEST MOISTURE": "-0.1",
          "Check_GROSS INCOME": "923.92",
          "Other_GROSS INCOME": 871.44,
          "Advantage_GROSS INCOME": "52.48"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0993AM1",
          "compTraits": "AM1",
          "compRM": 109,
          "compPT": null,
          "winPercentage": "54.8",
          "comps": 23,
          "checkWins": 17,
          "years": "13, 14",
          "isSummary": false,
          "Check_YIELD": "333.1",
          "Other_YIELD": 314.9,
          "Advantage_YIELD": "18.2",
          "Check_HARVEST MOISTURE": "27.5",
          "Other_HARVEST MOISTURE": 25,
          "Advantage_HARVEST MOISTURE": "-2.5",
          "Check_GROSS INCOME": "1082.33",
          "Other_GROSS INCOME": 1054.48,
          "Advantage_GROSS INCOME": "27.85"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1105AM",
          "compTraits": "AM",
          "compRM": 110,
          "compPT": null,
          "winPercentage": "14.8",
          "comps": 19,
          "checkWins": 4,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "346.2",
          "Other_YIELD": 353.6,
          "Advantage_YIELD": "-7.4",
          "Check_HARVEST MOISTURE": "23.7",
          "Other_HARVEST MOISTURE": 25.2,
          "Advantage_HARVEST MOISTURE": "1.5",
          "Check_GROSS INCOME": "1178.38",
          "Other_GROSS INCOME": 1182.27,
          "Advantage_GROSS INCOME": "-3.88"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1197AM",
          "compTraits": "AM",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "4.8",
          "comps": 14,
          "checkWins": 1,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "253.0",
          "Other_YIELD": 265.4,
          "Advantage_YIELD": "-12.4",
          "Check_HARVEST MOISTURE": "19.9",
          "Other_HARVEST MOISTURE": 20.9,
          "Advantage_HARVEST MOISTURE": "0.9",
          "Check_GROSS INCOME": "898.78",
          "Other_GROSS INCOME": 932.89,
          "Advantage_GROSS INCOME": "-34.11"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1365AMX",
          "compTraits": "AMXR",
          "compRM": 113,
          "compPT": null,
          "winPercentage": "33.3",
          "comps": 2,
          "checkWins": 1,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "241.3",
          "Other_YIELD": 243.9,
          "Advantage_YIELD": "-2.5",
          "Check_HARVEST MOISTURE": "16.7",
          "Other_HARVEST MOISTURE": 17.6,
          "Advantage_HARVEST MOISTURE": "0.9",
          "Check_GROSS INCOME": "888.37",
          "Other_GROSS INCOME": 889.17,
          "Advantage_GROSS INCOME": "-0.80"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0805AM",
          "compTraits": "AM",
          "compRM": 108,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "218.4",
          "Other_YIELD": 212,
          "Advantage_YIELD": "6.4",
          "Check_HARVEST MOISTURE": "15.9",
          "Other_HARVEST MOISTURE": 17.5,
          "Advantage_HARVEST MOISTURE": "1.6",
          "Check_GROSS INCOME": "810.96",
          "Other_GROSS INCOME": 773.57,
          "Advantage_GROSS INCOME": "37.39"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1324HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 113,
          "compPT": null,
          "winPercentage": "60.9",
          "comps": 17,
          "checkWins": 14,
          "years": "13, 14",
          "isSummary": false,
          "Check_YIELD": "215.5",
          "Other_YIELD": 203.4,
          "Advantage_YIELD": "12.0",
          "Check_HARVEST MOISTURE": "21.1",
          "Other_HARVEST MOISTURE": 21.4,
          "Advantage_HARVEST MOISTURE": "0.3",
          "Check_GROSS INCOME": "755.49",
          "Other_GROSS INCOME": 710.55,
          "Advantage_GROSS INCOME": "44.94"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1365",
          "compTraits": "AMX",
          "compRM": 113,
          "compPT": null,
          "winPercentage": "50.0",
          "comps": 1,
          "checkWins": 1,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "230.6",
          "Other_YIELD": 220.3,
          "Advantage_YIELD": "10.3",
          "Check_HARVEST MOISTURE": "14.9",
          "Other_HARVEST MOISTURE": 16.1,
          "Advantage_HARVEST MOISTURE": "1.2",
          "Check_GROSS INCOME": "864.88",
          "Other_GROSS INCOME": 816.48,
          "Advantage_GROSS INCOME": "48.41"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1498AM",
          "compTraits": "AM",
          "compRM": 114,
          "compPT": null,
          "winPercentage": "50.0",
          "comps": 15,
          "checkWins": 10,
          "years": "14, 15",
          "isSummary": false,
          "Check_YIELD": "218.6",
          "Other_YIELD": 205.6,
          "Advantage_YIELD": "12.9",
          "Check_HARVEST MOISTURE": "17.8",
          "Other_HARVEST MOISTURE": 19.6,
          "Advantage_HARVEST MOISTURE": "1.8",
          "Check_GROSS INCOME": "794.87",
          "Other_GROSS INCOME": 732.87,
          "Advantage_GROSS INCOME": "62.00"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1197CHR",
          "compTraits": "CHR",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "16.7",
          "comps": 5,
          "checkWins": 1,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "235.2",
          "Other_YIELD": 252.8,
          "Advantage_YIELD": "-17.6",
          "Check_HARVEST MOISTURE": "18.6",
          "Other_HARVEST MOISTURE": 19.7,
          "Advantage_HARVEST MOISTURE": "1.1",
          "Check_GROSS INCOME": "848.08",
          "Other_GROSS INCOME": 900.91,
          "Advantage_GROSS INCOME": "-52.83"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "33D53 AM1",
          "compTraits": "AM1",
          "compRM": 115,
          "compPT": null,
          "winPercentage": "75.0",
          "comps": 3,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "239.5",
          "Other_YIELD": 221.7,
          "Advantage_YIELD": "17.9",
          "Check_HARVEST MOISTURE": "15.3",
          "Other_HARVEST MOISTURE": 15.2,
          "Advantage_HARVEST MOISTURE": "-0.1",
          "Check_GROSS INCOME": "895.59",
          "Other_GROSS INCOME": 829.34,
          "Advantage_GROSS INCOME": "66.25"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690AM",
          "compTraits": "AM",
          "compRM": 116,
          "compPT": null,
          "winPercentage": "21.1",
          "comps": 13,
          "checkWins": 4,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "211.5",
          "Other_YIELD": 219.1,
          "Advantage_YIELD": "-7.7",
          "Check_HARVEST MOISTURE": "16.8",
          "Other_HARVEST MOISTURE": 18.1,
          "Advantage_HARVEST MOISTURE": "1.3",
          "Check_GROSS INCOME": "777.65",
          "Other_GROSS INCOME": 794.69,
          "Advantage_GROSS INCOME": "-17.05"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P2088AM",
          "compTraits": "AM",
          "compRM": 120,
          "compPT": null,
          "winPercentage": 0,
          "comps": 1,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "221.0",
          "Other_YIELD": 238.1,
          "Advantage_YIELD": "-17.2",
          "Check_HARVEST MOISTURE": "17.1",
          "Other_HARVEST MOISTURE": 22.2,
          "Advantage_HARVEST MOISTURE": "5.2",
          "Check_GROSS INCOME": "810.27",
          "Other_GROSS INCOME": 823.98,
          "Advantage_GROSS INCOME": "-13.71"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AM1",
          "compTraits": "AM1",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "51.2",
          "comps": 57,
          "checkWins": 41,
          "years": "13, 14",
          "isSummary": false,
          "Check_YIELD": "291.1",
          "Other_YIELD": 283.7,
          "Advantage_YIELD": "7.4",
          "Check_HARVEST MOISTURE": "22.8",
          "Other_HARVEST MOISTURE": 23.3,
          "Advantage_HARVEST MOISTURE": "0.5",
          "Check_GROSS INCOME": "1000.37",
          "Other_GROSS INCOME": 969.53,
          "Advantage_GROSS INCOME": "30.84"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1360HR",
          "compTraits": "RR/HX1/LL",
          "compRM": 113,
          "compPT": null,
          "winPercentage": "66.7",
          "comps": 2,
          "checkWins": 2,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "208.5",
          "Other_YIELD": 203.7,
          "Advantage_YIELD": "4.9",
          "Check_HARVEST MOISTURE": "17.7",
          "Other_HARVEST MOISTURE": 20,
          "Advantage_HARVEST MOISTURE": "2.3",
          "Check_GROSS INCOME": "759.57",
          "Other_GROSS INCOME": 722.89,
          "Advantage_GROSS INCOME": "36.69"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1266AM",
          "compTraits": "AM",
          "compRM": 112,
          "compPT": null,
          "winPercentage": "44.8",
          "comps": 68,
          "checkWins": 43,
          "years": "14, 15",
          "isSummary": false,
          "Check_YIELD": "294.6",
          "Other_YIELD": 292.6,
          "Advantage_YIELD": "2.0",
          "Check_HARVEST MOISTURE": "23.5",
          "Other_HARVEST MOISTURE": 23.6,
          "Advantage_HARVEST MOISTURE": "0.1",
          "Check_GROSS INCOME": "1004.26",
          "Other_GROSS INCOME": 996.84,
          "Advantage_GROSS INCOME": "7.41"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1625CHR",
          "compTraits": "CHR",
          "compRM": 116,
          "compPT": null,
          "winPercentage": "40.0",
          "comps": 8,
          "checkWins": 4,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "371.0",
          "Other_YIELD": 366.3,
          "Advantage_YIELD": "4.7",
          "Check_HARVEST MOISTURE": "27.6",
          "Other_HARVEST MOISTURE": 30.8,
          "Advantage_HARVEST MOISTURE": "3.2",
          "Check_GROSS INCOME": "1204.56",
          "Other_GROSS INCOME": 1141.85,
          "Advantage_GROSS INCOME": "62.71"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1271AM",
          "compTraits": "AM",
          "compRM": 112,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "217.7",
          "Other_YIELD": 218.4,
          "Advantage_YIELD": "-0.7",
          "Check_HARVEST MOISTURE": "16.0",
          "Other_HARVEST MOISTURE": 19.1,
          "Advantage_HARVEST MOISTURE": "3.1",
          "Check_GROSS INCOME": "807.95",
          "Other_GROSS INCOME": 783.57,
          "Advantage_GROSS INCOME": "24.38"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AMX",
          "compTraits": "AMX",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "44.0",
          "comps": 19,
          "checkWins": 11,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "219.7",
          "Other_YIELD": 226.8,
          "Advantage_YIELD": "-7.1",
          "Check_HARVEST MOISTURE": "17.1",
          "Other_HARVEST MOISTURE": 17.4,
          "Advantage_HARVEST MOISTURE": "0.3",
          "Check_GROSS INCOME": "805.41",
          "Other_GROSS INCOME": 828.84,
          "Advantage_GROSS INCOME": "-23.43"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151XR",
          "compTraits": "RR2/HXX/LL",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "40.0",
          "comps": 4,
          "checkWins": 3,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "242.6",
          "Other_YIELD": 245.4,
          "Advantage_YIELD": "-2.8",
          "Check_HARVEST MOISTURE": "16.4",
          "Other_HARVEST MOISTURE": 16.8,
          "Advantage_HARVEST MOISTURE": "0.4",
          "Check_GROSS INCOME": "896.06",
          "Other_GROSS INCOME": 902.52,
          "Advantage_GROSS INCOME": "-6.46"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC60-67RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690CHR",
          "compTraits": "CHR",
          "compRM": 116,
          "compPT": null,
          "winPercentage": "30.1",
          "comps": 73,
          "checkWins": 32,
          "years": "14, 15",
          "isSummary": false,
          "Check_YIELD": "379.9",
          "Other_YIELD": 392.5,
          "Advantage_YIELD": "-12.6",
          "Check_HARVEST MOISTURE": "28.8",
          "Other_HARVEST MOISTURE": 32.5,
          "Advantage_HARVEST MOISTURE": "3.6",
          "Check_GROSS INCOME": "1214.21",
          "Other_GROSS INCOME": 1197.46,
          "Advantage_GROSS INCOME": "16.75"
        }, {
          "Check_YIELD": "291.5",
          "Check_HARVEST MOISTURE": "22.8",
          "Check_GROSS INCOME": "994.48",
          "Other_YIELD": 284.2772887323944,
          "Other_HARVEST MOISTURE": 23.948063380281695,
          "Other_GROSS INCOME": 955.4437323943663,
          "Advantage_YIELD": "7.2",
          "Advantage_HARVEST MOISTURE": "1.1",
          "Advantage_GROSS INCOME": "39.03",
          "comps": 568,
          "winPercentage": "45.0",
          "checkTraits": "GENSSRIB",
          "checkRM": 110,
          "checkPT": "",
          "compBrand": "",
          "compProdBrand": "",
          "compTraits": "",
          "compRM": "",
          "compPT": "",
          "years": "",
          "isSummary": true
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151XR",
          "compTraits": "RR2/HXX/LL",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "40.0",
          "comps": 4,
          "checkWins": 2,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "240.0",
          "Other_YIELD": 245.4,
          "Advantage_YIELD": "-5.4",
          "Check_HARVEST MOISTURE": "15.3",
          "Other_HARVEST MOISTURE": 16.8,
          "Advantage_HARVEST MOISTURE": "1.5",
          "Check_GROSS INCOME": "897.27",
          "Other_GROSS INCOME": 902.52,
          "Advantage_GROSS INCOME": "-5.25"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1324HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 113,
          "compPT": null,
          "winPercentage": "42.1",
          "comps": 14,
          "checkWins": 8,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "177.6",
          "Other_YIELD": 175.9,
          "Advantage_YIELD": "1.8",
          "Check_HARVEST MOISTURE": "18.5",
          "Other_HARVEST MOISTURE": 19.4,
          "Advantage_HARVEST MOISTURE": "0.8",
          "Check_GROSS INCOME": "640.98",
          "Other_GROSS INCOME": 628.81,
          "Advantage_GROSS INCOME": "12.17"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0993AM1",
          "compTraits": "AM1",
          "compRM": 109,
          "compPT": null,
          "winPercentage": "8.3",
          "comps": 9,
          "checkWins": 1,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "200.5",
          "Other_YIELD": 206,
          "Advantage_YIELD": "-5.5",
          "Check_HARVEST MOISTURE": "16.7",
          "Other_HARVEST MOISTURE": 16.6,
          "Advantage_HARVEST MOISTURE": "-0.1",
          "Check_GROSS INCOME": "737.98",
          "Other_GROSS INCOME": 759.27,
          "Advantage_GROSS INCOME": "-21.29"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AM1",
          "compTraits": "AM1",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "53.3",
          "comps": 11,
          "checkWins": 8,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "216.8",
          "Other_YIELD": 204.9,
          "Advantage_YIELD": "11.9",
          "Check_HARVEST MOISTURE": "15.6",
          "Other_HARVEST MOISTURE": 16.3,
          "Advantage_HARVEST MOISTURE": "0.7",
          "Check_GROSS INCOME": "807.90",
          "Other_GROSS INCOME": 758.03,
          "Advantage_GROSS INCOME": "49.87"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AM",
          "compTraits": "AM",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "48.7",
          "comps": 30,
          "checkWins": 19,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "197.7",
          "Other_YIELD": 181.7,
          "Advantage_YIELD": "16.0",
          "Check_HARVEST MOISTURE": "20.7",
          "Other_HARVEST MOISTURE": 21.4,
          "Advantage_HARVEST MOISTURE": "0.7",
          "Check_GROSS INCOME": "696.31",
          "Other_GROSS INCOME": 634.92,
          "Advantage_GROSS INCOME": "61.40"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1498AM1",
          "compTraits": "AM1",
          "compRM": 114,
          "compPT": null,
          "winPercentage": "42.9",
          "comps": 31,
          "checkWins": 18,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "311.8",
          "Other_YIELD": 284,
          "Advantage_YIELD": "27.8",
          "Check_HARVEST MOISTURE": "22.2",
          "Other_HARVEST MOISTURE": 25.1,
          "Advantage_HARVEST MOISTURE": "2.9",
          "Check_GROSS INCOME": "1079.19",
          "Other_GROSS INCOME": 950.01,
          "Advantage_GROSS INCOME": "129.18"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0987AM1",
          "compTraits": "AM1",
          "compRM": 109,
          "compPT": null,
          "winPercentage": "35.7",
          "comps": 10,
          "checkWins": 5,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "261.9",
          "Other_YIELD": 259.7,
          "Advantage_YIELD": "2.2",
          "Check_HARVEST MOISTURE": "19.6",
          "Other_HARVEST MOISTURE": 21.6,
          "Advantage_HARVEST MOISTURE": "2.0",
          "Check_GROSS INCOME": "934.13",
          "Other_GROSS INCOME": 905.47,
          "Advantage_GROSS INCOME": "28.66"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0876CHR",
          "compTraits": "CHR",
          "compRM": 108,
          "compPT": null,
          "winPercentage": "66.7",
          "comps": 13,
          "checkWins": 12,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "246.2",
          "Other_YIELD": 234.6,
          "Advantage_YIELD": "11.6",
          "Check_HARVEST MOISTURE": "16.2",
          "Other_HARVEST MOISTURE": 18,
          "Advantage_HARVEST MOISTURE": "1.8",
          "Check_GROSS INCOME": "911.27",
          "Other_GROSS INCOME": 851.7,
          "Advantage_GROSS INCOME": "59.57"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1555CHR",
          "compTraits": "CHR",
          "compRM": 115,
          "compPT": null,
          "winPercentage": 0,
          "comps": 3,
          "checkWins": 0,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "222.5",
          "Other_YIELD": 244.9,
          "Advantage_YIELD": "-22.4",
          "Check_HARVEST MOISTURE": "18.5",
          "Other_HARVEST MOISTURE": 21,
          "Advantage_HARVEST MOISTURE": "2.4",
          "Check_GROSS INCOME": "803.04",
          "Other_GROSS INCOME": 860.18,
          "Advantage_GROSS INCOME": "-57.15"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0832AM1",
          "compTraits": "AM1",
          "compRM": 108,
          "compPT": null,
          "winPercentage": "20.0",
          "comps": 3,
          "checkWins": 1,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "234.5",
          "Other_YIELD": 236.2,
          "Advantage_YIELD": "-1.7",
          "Check_HARVEST MOISTURE": "15.1",
          "Other_HARVEST MOISTURE": 16.5,
          "Advantage_HARVEST MOISTURE": "1.4",
          "Check_GROSS INCOME": "878.38",
          "Other_GROSS INCOME": 871.44,
          "Advantage_GROSS INCOME": "6.94"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1023AM-R",
          "compTraits": "AMR",
          "compRM": 110,
          "compPT": null,
          "winPercentage": "60.0",
          "comps": 4,
          "checkWins": 3,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "240.0",
          "Other_YIELD": 238.3,
          "Advantage_YIELD": "1.7",
          "Check_HARVEST MOISTURE": "15.3",
          "Other_HARVEST MOISTURE": 16.7,
          "Advantage_HARVEST MOISTURE": "1.4",
          "Check_GROSS INCOME": "897.27",
          "Other_GROSS INCOME": 877.21,
          "Advantage_GROSS INCOME": "20.06"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 116,
          "compPT": null,
          "winPercentage": 0,
          "comps": 4,
          "checkWins": 0,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "240.0",
          "Other_YIELD": 257.7,
          "Advantage_YIELD": "-17.6",
          "Check_HARVEST MOISTURE": "15.3",
          "Other_HARVEST MOISTURE": 18.7,
          "Advantage_HARVEST MOISTURE": "3.4",
          "Check_GROSS INCOME": "897.27",
          "Other_GROSS INCOME": 927.98,
          "Advantage_GROSS INCOME": "-30.71"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0993XR",
          "compTraits": "RR2/HXX/LL",
          "compRM": 109,
          "compPT": null,
          "winPercentage": 0,
          "comps": 1,
          "checkWins": 0,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "188.3",
          "Other_YIELD": 206.8,
          "Advantage_YIELD": "-18.5",
          "Check_HARVEST MOISTURE": "18.4",
          "Other_HARVEST MOISTURE": 19,
          "Advantage_HARVEST MOISTURE": "0.5",
          "Check_GROSS INCOME": "680.47",
          "Other_GROSS INCOME": 742.96,
          "Advantage_GROSS INCOME": "-62.49"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0636HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 106,
          "compPT": null,
          "winPercentage": "66.7",
          "comps": 2,
          "checkWins": 2,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "182.7",
          "Other_YIELD": 163.4,
          "Advantage_YIELD": "19.3",
          "Check_HARVEST MOISTURE": "23.2",
          "Other_HARVEST MOISTURE": 21.9,
          "Advantage_HARVEST MOISTURE": "-1.3",
          "Check_GROSS INCOME": "625.33",
          "Other_GROSS INCOME": 567.4,
          "Advantage_GROSS INCOME": "57.93"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P0636AM1",
          "compTraits": "AM1",
          "compRM": 106,
          "compPT": null,
          "winPercentage": "37.5",
          "comps": 6,
          "checkWins": 3,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "168.2",
          "Other_YIELD": 174,
          "Advantage_YIELD": "-5.8",
          "Check_HARVEST MOISTURE": "18.3",
          "Other_HARVEST MOISTURE": 19.2,
          "Advantage_HARVEST MOISTURE": "0.9",
          "Check_GROSS INCOME": "608.51",
          "Other_GROSS INCOME": 623.29,
          "Advantage_GROSS INCOME": "-14.78"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1625CHR",
          "compTraits": "CHR",
          "compRM": 116,
          "compPT": null,
          "winPercentage": 0,
          "comps": 4,
          "checkWins": 0,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "240.0",
          "Other_YIELD": 253.6,
          "Advantage_YIELD": "-13.5",
          "Check_HARVEST MOISTURE": "15.3",
          "Other_HARVEST MOISTURE": 19,
          "Advantage_HARVEST MOISTURE": "3.7",
          "Check_GROSS INCOME": "897.27",
          "Other_GROSS INCOME": 910.66,
          "Advantage_GROSS INCOME": "-13.39"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690CHR",
          "compTraits": "CHR",
          "compRM": 116,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "241.6",
          "Other_YIELD": 278.7,
          "Advantage_YIELD": "-37.1",
          "Check_HARVEST MOISTURE": "14.2",
          "Other_HARVEST MOISTURE": 18.4,
          "Advantage_HARVEST MOISTURE": "4.1",
          "Check_GROSS INCOME": "905.85",
          "Other_GROSS INCOME": 1007.48,
          "Advantage_GROSS INCOME": "-101.63"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC61-16RIB",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1105AM",
          "compTraits": "AM",
          "compRM": 110,
          "compPT": null,
          "winPercentage": 0,
          "comps": 2,
          "checkWins": 0,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "241.6",
          "Other_YIELD": 276.2,
          "Advantage_YIELD": "-34.6",
          "Check_HARVEST MOISTURE": "14.2",
          "Other_HARVEST MOISTURE": 16.3,
          "Advantage_HARVEST MOISTURE": "2.1",
          "Check_GROSS INCOME": "905.85",
          "Other_GROSS INCOME": 1021.18,
          "Advantage_GROSS INCOME": "-115.33"
        }, {
          "Check_YIELD": "234.2",
          "Check_HARVEST MOISTURE": "18.8",
          "Check_GROSS INCOME": "840.79",
          "Other_YIELD": 226.03267973856208,
          "Other_HARVEST MOISTURE": 20.360130718954252,
          "Other_GROSS INCOME": 797.0128758169935,
          "Advantage_YIELD": "8.2",
          "Advantage_HARVEST MOISTURE": "1.6",
          "Advantage_GROSS INCOME": "43.78",
          "comps": 153,
          "winPercentage": "39.8",
          "checkTraits": "GENSSRIB",
          "checkRM": 111,
          "checkPT": "",
          "compBrand": "",
          "compProdBrand": "",
          "compTraits": "",
          "compRM": "",
          "compPT": "",
          "years": "",
          "isSummary": true
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-78RIB",
          "checkTraits": "GENDGVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1197AM",
          "compTraits": "AM",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "5.6",
          "comps": 12,
          "checkWins": 1,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "250.5",
          "Other_YIELD": 272.5,
          "Advantage_YIELD": "-22.0",
          "Check_HARVEST MOISTURE": "20.4",
          "Other_HARVEST MOISTURE": 21.4,
          "Advantage_HARVEST MOISTURE": "1.0",
          "Check_GROSS INCOME": "885.54",
          "Other_GROSS INCOME": 952.25,
          "Advantage_GROSS INCOME": "-66.71"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-78RIB",
          "checkTraits": "GENDGVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AM",
          "compTraits": "AM",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "53.3",
          "comps": 9,
          "checkWins": 8,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "247.2",
          "Other_YIELD": 238.6,
          "Advantage_YIELD": "8.6",
          "Check_HARVEST MOISTURE": "20.1",
          "Other_HARVEST MOISTURE": 21,
          "Advantage_HARVEST MOISTURE": "0.9",
          "Check_GROSS INCOME": "876.79",
          "Other_GROSS INCOME": 837.34,
          "Advantage_GROSS INCOME": "39.46"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-78RIB",
          "checkTraits": "GENDGVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P2088AM",
          "compTraits": "AM",
          "compRM": 120,
          "compPT": null,
          "winPercentage": 0,
          "comps": 1,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "193.1",
          "Other_YIELD": 238.1,
          "Advantage_YIELD": "-45.0",
          "Check_HARVEST MOISTURE": "17.0",
          "Other_HARVEST MOISTURE": 22.2,
          "Advantage_HARVEST MOISTURE": "5.3",
          "Check_GROSS INCOME": "708.82",
          "Other_GROSS INCOME": 823.98,
          "Advantage_GROSS INCOME": "-115.16"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-78RIB",
          "checkTraits": "GENDGVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690CHR",
          "compTraits": "CHR",
          "compRM": 116,
          "compPT": null,
          "winPercentage": "43.5",
          "comps": 15,
          "checkWins": 10,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "233.1",
          "Other_YIELD": 232,
          "Advantage_YIELD": "1.1",
          "Check_HARVEST MOISTURE": "19.2",
          "Other_HARVEST MOISTURE": 22,
          "Advantage_HARVEST MOISTURE": "2.8",
          "Check_GROSS INCOME": "834.58",
          "Other_GROSS INCOME": 805.2,
          "Advantage_GROSS INCOME": "29.38"
        }, {
          "Check_YIELD": "241.1",
          "Check_HARVEST MOISTURE": "19.7",
          "Check_GROSS INCOME": "857.98",
          "Other_YIELD": 246.90540540540542,
          "Other_HARVEST MOISTURE": 21.56756756756757,
          "Other_GROSS INCOME": 861.2172972972974,
          "Advantage_YIELD": "-5.8",
          "Advantage_HARVEST MOISTURE": "1.8",
          "Advantage_GROSS INCOME": "-3.24",
          "comps": 37,
          "winPercentage": "32.4",
          "checkTraits": "GENDGVT2PRIB",
          "checkRM": 112,
          "checkPT": "",
          "compBrand": "",
          "compProdBrand": "",
          "compTraits": "",
          "compRM": "",
          "compPT": "",
          "years": "",
          "isSummary": true
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "33D42-INTRASECT",
          "compTraits": "INTRASECT",
          "compRM": 115,
          "compPT": null,
          "winPercentage": "16.7",
          "comps": 5,
          "checkWins": 1,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "194.3",
          "Other_YIELD": 207.2,
          "Advantage_YIELD": "-12.9",
          "Check_HARVEST MOISTURE": "16.4",
          "Other_HARVEST MOISTURE": 17.6,
          "Advantage_HARVEST MOISTURE": "1.1",
          "Check_GROSS INCOME": "717.68",
          "Other_GROSS INCOME": 755.65,
          "Advantage_GROSS INCOME": "-37.98"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690CHR",
          "compTraits": "CHR",
          "compRM": 116,
          "compPT": null,
          "winPercentage": "35.1",
          "comps": 69,
          "checkWins": 34,
          "years": "14, 15",
          "isSummary": false,
          "Check_YIELD": "386.3",
          "Other_YIELD": 387.6,
          "Advantage_YIELD": "-1.3",
          "Check_HARVEST MOISTURE": "29.3",
          "Other_HARVEST MOISTURE": 32.2,
          "Advantage_HARVEST MOISTURE": "2.9",
          "Check_GROSS INCOME": "1228.20",
          "Other_GROSS INCOME": 1186.8,
          "Advantage_GROSS INCOME": "41.40"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1197AM",
          "compTraits": "AM",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "8.3",
          "comps": 7,
          "checkWins": 1,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "277.5",
          "Other_YIELD": 299.1,
          "Advantage_YIELD": "-21.6",
          "Check_HARVEST MOISTURE": "24.0",
          "Other_HARVEST MOISTURE": 23.5,
          "Advantage_HARVEST MOISTURE": "-0.5",
          "Check_GROSS INCOME": "940.41",
          "Other_GROSS INCOME": 1019.33,
          "Advantage_GROSS INCOME": "-78.92"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1105AM",
          "compTraits": "AM",
          "compRM": 110,
          "compPT": null,
          "winPercentage": "11.1",
          "comps": 19,
          "checkWins": 3,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "342.6",
          "Other_YIELD": 353.6,
          "Advantage_YIELD": "-11.0",
          "Check_HARVEST MOISTURE": "24.1",
          "Other_HARVEST MOISTURE": 25.2,
          "Advantage_HARVEST MOISTURE": "1.0",
          "Check_GROSS INCOME": "1159.64",
          "Other_GROSS INCOME": 1182.27,
          "Advantage_GROSS INCOME": "-22.62"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P2088AM",
          "compTraits": "AM",
          "compRM": 120,
          "compPT": null,
          "winPercentage": 0,
          "comps": 1,
          "checkWins": 0,
          "years": "15",
          "isSummary": false,
          "Check_YIELD": "213.0",
          "Other_YIELD": 238.1,
          "Advantage_YIELD": "-25.2",
          "Check_HARVEST MOISTURE": "18.1",
          "Other_HARVEST MOISTURE": 22.2,
          "Advantage_HARVEST MOISTURE": "4.1",
          "Check_GROSS INCOME": "772.14",
          "Other_GROSS INCOME": 823.98,
          "Advantage_GROSS INCOME": "-51.84"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1690AM",
          "compTraits": "AM",
          "compRM": 116,
          "compPT": null,
          "winPercentage": "40.0",
          "comps": 14,
          "checkWins": 8,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "227.9",
          "Other_YIELD": 221.2,
          "Advantage_YIELD": "6.8",
          "Check_HARVEST MOISTURE": "17.0",
          "Other_HARVEST MOISTURE": 18.6,
          "Advantage_HARVEST MOISTURE": "1.7",
          "Check_GROSS INCOME": "836.95",
          "Other_GROSS INCOME": 797.25,
          "Advantage_GROSS INCOME": "39.71"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1266AM",
          "compTraits": "AM",
          "compRM": 112,
          "compPT": null,
          "winPercentage": "41.5",
          "comps": 38,
          "checkWins": 22,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "314.2",
          "Other_YIELD": 309.4,
          "Advantage_YIELD": "4.8",
          "Check_HARVEST MOISTURE": "24.9",
          "Other_HARVEST MOISTURE": 24.3,
          "Advantage_HARVEST MOISTURE": "-0.6",
          "Check_GROSS INCOME": "1053.91",
          "Other_GROSS INCOME": 1044.8,
          "Advantage_GROSS INCOME": "9.11"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AMX",
          "compTraits": "AMX",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "35.7",
          "comps": 11,
          "checkWins": 5,
          "years": "14",
          "isSummary": false,
          "Check_YIELD": "214.1",
          "Other_YIELD": 216.8,
          "Advantage_YIELD": "-2.7",
          "Check_HARVEST MOISTURE": "15.2",
          "Other_HARVEST MOISTURE": 15.3,
          "Advantage_HARVEST MOISTURE": "0.1",
          "Check_GROSS INCOME": "801.19",
          "Other_GROSS INCOME": 810.8,
          "Advantage_GROSS INCOME": "-9.61"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AM1",
          "compTraits": "AM1",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "54.5",
          "comps": 31,
          "checkWins": 24,
          "years": "13, 14",
          "isSummary": false,
          "Check_YIELD": "311.0",
          "Other_YIELD": 294.9,
          "Advantage_YIELD": "16.1",
          "Check_HARVEST MOISTURE": "24.3",
          "Other_HARVEST MOISTURE": 24,
          "Advantage_HARVEST MOISTURE": "-0.4",
          "Check_GROSS INCOME": "1050.26",
          "Other_GROSS INCOME": 1000.05,
          "Advantage_GROSS INCOME": "50.21"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1151AM",
          "compTraits": "AM",
          "compRM": 111,
          "compPT": null,
          "winPercentage": "50.0",
          "comps": 29,
          "checkWins": 21,
          "years": "13, 14, 15",
          "isSummary": false,
          "Check_YIELD": "263.8",
          "Other_YIELD": 251.8,
          "Advantage_YIELD": "12.0",
          "Check_HARVEST MOISTURE": "23.5",
          "Other_HARVEST MOISTURE": 23,
          "Advantage_HARVEST MOISTURE": "-0.4",
          "Check_GROSS INCOME": "900.04",
          "Other_GROSS INCOME": 863.3,
          "Advantage_GROSS INCOME": "36.74"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1498AM1",
          "compTraits": "AM1",
          "compRM": 114,
          "compPT": null,
          "winPercentage": "66.7",
          "comps": 4,
          "checkWins": 4,
          "years": "13, 14",
          "isSummary": false,
          "Check_YIELD": "223.4",
          "Other_YIELD": 212.9,
          "Advantage_YIELD": "10.5",
          "Check_HARVEST MOISTURE": "18.6",
          "Other_HARVEST MOISTURE": 18.9,
          "Advantage_HARVEST MOISTURE": "0.3",
          "Check_GROSS INCOME": "805.39",
          "Other_GROSS INCOME": 764.92,
          "Advantage_GROSS INCOME": "40.46"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1324HR",
          "compTraits": "RR2/HX1/LL",
          "compRM": 113,
          "compPT": null,
          "winPercentage": "55.6",
          "comps": 7,
          "checkWins": 5,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "170.5",
          "Other_YIELD": 166.9,
          "Advantage_YIELD": "3.6",
          "Check_HARVEST MOISTURE": "23.2",
          "Other_HARVEST MOISTURE": 23.3,
          "Advantage_HARVEST MOISTURE": 0,
          "Check_GROSS INCOME": "582.98",
          "Other_GROSS INCOME": 570.59,
          "Advantage_GROSS INCOME": "12.39"
        }, {
          "checkBrand": "DEKALB",
          "checkProdBrand": "DKC62-98RIB",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "BB",
          "compBrand": "PIONEER",
          "compProdBrand": "P1768AMX",
          "compTraits": "AMX",
          "compRM": 117,
          "compPT": null,
          "winPercentage": "50.0",
          "comps": 1,
          "checkWins": 1,
          "years": "13",
          "isSummary": false,
          "Check_YIELD": "172.8",
          "Other_YIELD": 167.1,
          "Advantage_YIELD": "5.7",
          "Check_HARVEST MOISTURE": "18.1",
          "Other_HARVEST MOISTURE": 19,
          "Advantage_HARVEST MOISTURE": "0.8",
          "Check_GROSS INCOME": "626.31",
          "Other_GROSS INCOME": 600.29,
          "Advantage_GROSS INCOME": "26.01"
        }, {
          "Check_YIELD": "310.7",
          "Check_HARVEST MOISTURE": "24.5",
          "Check_GROSS INCOME": "1037.67",
          "Other_YIELD": 308.05296610169495,
          "Other_HARVEST MOISTURE": 25.407203389830514,
          "Other_GROSS INCOME": 1015.1013559322032,
          "Advantage_YIELD": "2.7",
          "Advantage_HARVEST MOISTURE": "0.9",
          "Advantage_GROSS INCOME": "22.57",
          "comps": 236,
          "winPercentage": "38.8",
          "checkTraits": "GENVT2PRIB",
          "checkRM": 112,
          "checkPT": "",
          "compBrand": "",
          "compProdBrand": "",
          "compTraits": "",
          "compRM": "",
          "compPT": "",
          "years": "",
          "isSummary": true
        }],
        "columns": [{
          "title": "Business Brand",
          "name": "checkBrand",
          "dataKey": "checkBrand",
          "$$hashKey": "object:8698"
        }, {
          "title": "Product Brand",
          "name": "checkProdBrand",
          "dataKey": "checkProdBrand",
          "$$hashKey": "object:8699"
        }, {
          "title": "Traits",
          "name": "checkTraits",
          "dataKey": "checkTraits",
          "$$hashKey": "object:8700"
        }, {
          "title": "RM",
          "name": "checkRM",
          "dataKey": "checkRM",
          "$$hashKey": "object:8701"
        }, {
          "title": "Type",
          "name": "checkPT",
          "dataKey": "checkPT",
          "$$hashKey": "object:8702"
        }, {
          "title": "Business Brand",
          "name": "compBrand",
          "dataKey": "compBrand",
          "$$hashKey": "object:8703"
        }, {
          "title": "Product Brand",
          "name": "compProdBrand",
          "dataKey": "compProdBrand",
          "$$hashKey": "object:8704"
        }, {
          "title": "Traits",
          "name": "compTraits",
          "dataKey": "compTraits",
          "$$hashKey": "object:8705"
        }, {
          "title": "RM",
          "name": "compRM",
          "dataKey": "compRM",
          "$$hashKey": "object:8706"
        }, {
          "title": "Type",
          "name": "compPT",
          "dataKey": "compPT",
          "$$hashKey": "object:8707"
        }, {
          "title": "Comps",
          "name": "comps",
          "dataKey": "comps",
          "$$hashKey": "object:8708"
        }, {
          "title": "Years",
          "name": "years",
          "dataKey": "years",
          "$$hashKey": "object:8709"
        }, {
          "title": "Win %",
          "name": "winPercentage",
          "dataKey": "winPercentage",
          "$$hashKey": "object:8710"
        }, {
          "title": "Check",
          "name": "Check_YIELD",
          "dataKey": "Check_YIELD",
          "$$hashKey": "object:8711"
        }, {
          "title": "Other",
          "name": "Other_YIELD",
          "dataKey": "Other_YIELD",
          "$$hashKey": "object:8712"
        }, {
          "title": "Advantage",
          "name": "Advantage_YIELD",
          "dataKey": "Advantage_YIELD",
          "$$hashKey": "object:8713"
        }, {
          "title": "Check",
          "name": "Check_HARVEST MOISTURE",
          "dataKey": "Check_HARVEST MOISTURE",
          "$$hashKey": "object:8714"
        }, {
          "title": "Other",
          "name": "Other_HARVEST MOISTURE",
          "dataKey": "Other_HARVEST MOISTURE",
          "$$hashKey": "object:8715"
        }, {
          "title": "Advantage",
          "name": "Advantage_HARVEST MOISTURE",
          "dataKey": "Advantage_HARVEST MOISTURE",
          "$$hashKey": "object:8716"
        }, {
          "title": "Check",
          "name": "Check_GROSS INCOME",
          "dataKey": "Check_GROSS INCOME",
          "$$hashKey": "object:8717"
        }, {
          "title": "Other",
          "name": "Other_GROSS INCOME",
          "dataKey": "Other_GROSS INCOME",
          "$$hashKey": "object:8718"
        }, {
          "title": "Advantage",
          "name": "Advantage_GROSS INCOME",
          "dataKey": "Advantage_GROSS INCOME",
          "$$hashKey": "object:8719"
        }],
        "categories": [{
          "title": "CHECK PRODUCTS",
          "colspan": 5,
          "colspanpdf": 5,
          "padding": 75,
          "$$hashKey": "object:8669"
        }, {
          "title": "OTHER PRODUCTS",
          "colspan": 5,
          "colspanpdf": 5,
          "padding": 75,
          "$$hashKey": "object:8670"
        }, {
          "title": "PERFORMANCE",
          "colspan": 3,
          "colspanpdf": 3,
          "padding": 24,
          "$$hashKey": "object:8671"
        }, {
          "title": "YIELD",
          "colspan": 3,
          "colspanpdf": 3,
          "padding": 32,
          "unit": "BUSHELS(56#)/ACRE",
          "$$hashKey": "object:8672"
        }, {
          "title": "HARVEST MOISTURE",
          "colspan": 3,
          "colspanpdf": 3,
          "padding": 3,
          "unit": "%",
          "$$hashKey": "object:8673"
        }, {
          "title": "GROSS INCOME",
          "colspan": 3,
          "colspanpdf": 3,
          "padding": 12,
          "unit": "$",
          "$$hashKey": "object:8674"
        }]
      }
};
/* GET home page. */
router.get('/', function (req, res, next) {
  var data = [
    ["title", "1"]
  ];
  res.render('index', sampleData);
  // startup(data, res);
});

/* POST home page. */
router.post('/', function (req, res, next) {
  var response = JSON.parse(req.body.data);
  console.log(response.data);
  var dataJSON = JSON.stringify(response.data);
  var dataObj = {
    data: dataJSON
  };
  var data = mapObj(dataObj);
  startup(data, res);
});

router.get('/pdf/', function (req, res, next) {
  var data = sampleData;
  res.render('pdf', data);
});

router.post('/pdf/', function (req, res, next) {
  var data = JSON.parse(req.body.data);

  console.log(data);
  //var data = sampleData;
  res.render('pdf', data);
});

function startup(data, res) {
  var pdfGen = genPDF(data);
  console.log('Data: ' + data);
  pdfGen.on('finish', function () {
    res.download('BriefSummary.pdf', 'BriefSummary.pdf');
  });
}

function mapObj(o) {
  return reducer(o);
}

function reducer(x) {
  var keys = getKeys(x);
  return mapper(keys, x);
}

function getKeys(obj) {
  return Object.keys(obj);
}

function mapper(y, x) {
  return y.map(function (k) {
    if (typeof x[k] === "object") {
      return [k, reducer(x[k])];
    }
    return [k, x[k]]
  });
}

function genPDF(data) {
  //var customHeader = {'Content-Type': 'application/x-www-form-urlencoded'}
  //var url = 'https://immense-springs-99065.herokuapp.com/';
  //var url = 'http://localhost:5000/'

  var url = 'https://warm-badlands-52758.herokuapp.com/';
  var write = fs.createWriteStream('BriefSummary.pdf');
  // URL
  wkhtmltopdf(url + 'pdf', {
      pageSize: 'letter',
      orientation: 'landscape',
      printMediaType: true,
      post: data
    })
    .pipe(write);

  return write;
}

module.exports = router;
